
<style>
label {
	text-align: center;
}
</style>

		<form method="post" action="<?=$this->url();?>">
			<label for="name">Gebruikersnaam:</label> <input type="text"
				name="username" id="username" placeholder="Gebruikersnaam" value=""
				class="ui-input-text ui-body-c ui-corner-all ui-shadow-inset"> <label
				for="name">Wachtwoord:</label> <input type="password"
				name="password" id="password" placeholder="Wachtwoord" value=""
				class="ui-input-text ui-body-c ui-corner-all ui-shadow-inset">
				<input type="submit" value="Inloggen" />
		</form>
