
<div data-theme="a" data-form="ui-body-a"class="ui-body ui-body-a ui-corner-all">

<h2>Registreer</h2>
	<form method="post" action="<?$this->url();?>">
	<div data-role="fieldcontain" class="ui-field-contain ui-body ui-br">
		<div data-role="fieldcontain">
		<label for="username">Username:</label>
			<input type="text" name="username" 
				class="ui-input-text ui-body-c ui-corner-all ui-shadow-inset ui-mini" />
		</div>
		<div data-role="fieldcontain">
		<label for="email">Email:</label>
		
			<input type="text" name="email"
				class="ui-input-text ui-body-c ui-corner-all ui-shadow-inset ui-mini" />
		</div>
		<div data-role="fieldcontain">
		<label for="tel">Telefoon-nummer:</label>
			<input type="text" name="tel"
				class="ui-input-text ui-body-c ui-corner-all ui-shadow-inset ui-mini" />
		</div>
		<div data-role="fieldcontain">
		<label for="pw1">Password:</label>
		<input type="password" name="pw1"
				class="ui-input-text ui-body-c ui-corner-all ui-shadow-inset ui-mini" />
		</div>
		<div data-role="fieldcontain">
		<label for="pw2">Bevestig password:</label>
			<input type="password" name="pw2"
				class="ui-input-text ui-body-c ui-corner-all ui-shadow-inset ui-mini" />
		</div>
		<div data-role="fieldContain">
			<input type="submit" class="ui-btn ui-shadow ui-btn-corner-all ui-btn-inline ui-btn-up-c" value="Opslaan"/>
		</div>
		</div>
	</form>
</div>