<html>
<head>
<title>Ns - Questionnaire</title>
<script type="text/javascript"
	src="<?= $this->baseUrl("js/bootstrap.min.js")?>"></script>
<link href="<?= $this->baseUrl("css/bootstrap.min.css")?>"
	rel="stylesheet">
</head>
<body>
	<header>
		<div class='container'>
			<div class='col-md-3'></div>
			<div id="login-box" class='col-md-6 col-md-offset-3'>
				<div class='col-md-5'></div>

				<div class='col-md-5'></div>

				<div class='col-md-2'></div>
				</form>
			</div>
		</div>
	</header>
	<nav>
		<div class='container'>
			<div class='col-md-5'>
				<div class='nav-text upper text-left bold'></div>
			</div>
			<div class='col-md-3 col-md-offset-1 text  -center'></div>
		</div>
	</nav>
	<section style='margin-bottom: 140px;'>
		<div class='container'>
    		<?=$this->layout()->content;?>
    	</div>
	</section>
	<footer>
		<div class='container text-center'></div>
	</footer>




</body>
</html>