<html>
<head>
<title>Ns - Questionnaire</title>
<script type="text/javascript"
	src="<?= $this->baseUrl("js/bootstrap.min.js")?>"></script>
<link href="<?= $this->baseUrl("css/bootstrap.min.css")?>"
	rel="stylesheet">
<link href="<?= $this->baseUrl("css/admin.css")?>"
	rel="stylesheet">
</head>
<body style='background:#fcb501'>
<div class="container" style="margin-top:30px">
<div class="col-md-4 col-md-offset-4">
    <div class="panel panel-default">
  <div class="panel-heading" style='background:#171771;color:#fff;border:0'><h3 class="panel-title"><strong>Inloggen </strong></h3></div>
  <div class="panel-body">
   <?=$this->layout()->content;?>
  </div>
</div>
</div>
</div>

</body>
</html>