<html>
<head>
<title>Ns - Questionnaire</title>
<script type="text/javascript"
	src="<?= $this->baseUrl("js/bootstrap.min.js")?>"></script>
<link href="<?= $this->baseUrl("css/bootstrap.min.css")?>"
	rel="stylesheet">
<link href="<?= $this->baseUrl("css/admin.css")?>"
	rel="stylesheet">
</head>
<body>
<div class="container" style="margin-top:30px">
<div class="col-md-4 col-md-offset-4">
    <div class="panel panel-default">
  <div class="panel-heading"><h3 class="panel-title"><strong>Inloggen </strong></h3></div>
  <div class="panel-body">
   <form role="form">
  <div class="form-group">
    <label for="exampleInputEmail1">Gebruikersnaam</label>
    <input type="email" class="form-control" style="border-radius:0px" id="exampleInputEmail1" placeholder="Gebruikersnaam">
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Wachtwoord</label>
    <input type="password" class="form-control" style="border-radius:0px" id="exampleInputPassword1" placeholder="Wachtwoord">
  </div>
  <button type="submit" class="btn btn-sm btn-default">Inloggen</button>
</form>
  </div>
</div>
</div>
</div>

</body>
</html>