<?php /*<!DOCTYPE html> 
<html> 
	<title>Ns - Questionnaire</title>
    	<meta name="viewport" content="width=device-width, initial-scale=1"> 
		<link href="<?= $this->baseUrl("css/jquery.mobile.custom.structure.min.css")?>" rel="stylsheet"/>
		<link href="<?= $this->baseUrl("css/jquery.mobile.custom.theme.min.css")?>" rel="stylsheet"/>
		
		<script type="text/javascript" src="http://code.jquery.com/jquery-1.6.4.min.js"></script>
		<script type="text/javascript" src="http://code.jquery.com/mobile/1.0/jquery.mobile-1.0.min.js"></script>
	</head>
<body> 

    <div data-role="header">
		<h1>My Title</h1>
	</div><!-- /header -->

	<div data-role="content">	
		<p>Hello world</p>		
	</div><!-- /content -->

</body>
</html>*/?>
<!DOCTYPE html> 
<html> 
	<head> 
	<title>My Page</title> 
	<meta name="viewport" content="width=device-width, initial-scale=1"> 
	<meta name="mobile-web-app-capable" content="yes">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<script type="text/javascript" src="<?=$this->baseUrl('js/jquery-1.10.2.js');?>"></script>
	<script type="text/javascript" src="<?=$this->baseUrl('js/jquery.mobile-1.4.2.min.js');?>"></script>
	<link rel="stylesheet" href="<?=$this->baseUrl('css/jquery.mobile-1.4.2.min.css');?>" />
	<link rel="stylesheet" href="<?=$this->baseUrl('css/NS.min.css');?>" />
	<link rel="stylesheet" href="<?=$this->baseUrl('css/jquery.mobile.icons.min.css');?>" />
	<link href="<?= $this->baseUrl("css/style.css")?>" rel="stylesheet"/>
	<link rel="apple-touch-icon" href="<?=$this->baseUrl('images/app-icon.png');?>" />
	<link rel="icon" sizes="196x196" href="<?=$this->baseUrl('images/app-icon.png');?>" />
</head> 
<body> 
<div data-role="page">
	<div data-role="header" data-add-back-btn="true">
		<h1>NS Survey App</h1>
	   <?php 	$auth = Zend_Auth::getInstance();
			if ($auth->hasIdentity()) : ?>
	   <a href="#nav-panel" data-icon="bars" data-iconpos="notext" class="ui-btn-right ui-btn ui-shadow ui-btn-corner-all ui-btn-icon-notext ui-btn-up-f" data-corners="true" data-shadow="true" data-iconshadow="true" data-wrapperels="span" data-theme="c" title="Menu"><span class="ui-btn-inner"><span class="ui-btn-text">Menu</span><span class="ui-icon ui-icon-bars ui-icon-shadow">&nbsp;</span></span></a>
	   <?php endif;?>
	</div>
	<div data-role="panel" data-position="right" data-position-fixed="false" data-display="reveal" id="nav-panel" data-theme="c" class="ui-panel ui-panel-position-left ui-panel-display-reveal ui-body-a ui-panel-animate ui-panel-closed">
		<div class="ui-panel-inner">
			<ul data-role="listview" data-theme="c" data-divider-theme="c" style="margin-top:-16px;" class="nav-search ui-listview">
			<li data-icon="delete" style="background-color:#111;" data-corners="false" data-shadow="false" data-iconshadow="true" data-wrapperels="div" data-iconpos="left" data-theme="c" class="ui-btn ui-btn-up-a ui-btn-icon-right ui-li-has-arrow ui-li ui-first-child"><div class="ui-btn-inner ui-li"><div class="ui-btn-text">
							<a href="#" data-rel="close" class="ui-link-inherit">Close menu</a>
						</div><span class="ui-icon ui-icon-delete ui-icon-shadow">&nbsp;</span></div></li>
						<li data-filtertext="wai-aria voiceover accessibility screen reader" data-corners="false" data-shadow="false" data-iconshadow="true" data-wrapperels="div" data-icon="arrow-r" data-iconpos="left" data-theme="c" class="ui-btn ui-btn-up-a ui-btn-icon-right ui-li-has-arrow ui-li"><div class="ui-btn-inner ui-li"><div class="ui-btn-text">
							<a href="../about/accessibility.html" class="ui-link-inherit">Accessibility</a>
						</div><span class="ui-icon ui-icon-arrow-r ui-icon-shadow">&nbsp;</span></div></li>
			</ul>
		</div>
	</div>
	<div data-role="content">

	<?=$this->layout()->content;?>
		</div>
<div data-role="footer">NS Survey App</div>

</div>
		
</body>
</html>