<!DOCTYPE html> 
<html> 
	<title>Ns - Questionnaire</title>
		<script type="text/javascript" src="<?= $this->baseUrl("js/jquery.mobile.custom.min.js");?>"></script>
		<link href="<?= $this->baseUrl("css/jquery.mobile.custom.theme.min.css")?>" rel="stylsheet"/>
		<link href="<?= $this->baseUrl("css/jquery.mobile.custom.structure.min.css")?>" rel="stylsheet"/>
		<link href="<?= $this->baseUrl("css/style.css")?>" rel="stylesheet"/>
    	<meta name="viewport" content="width=device-width, initial-scale=1"> 
	</head>
<body> 

    <div data-role="page">
    	<?=$this->layout()->content;?>
    </div>

</body>
</html>