<a onclick="window.history.go(-1)" class='btn btn-primary'>Terug</a>
<h3>Gebruiker toevoegen</h3>
<form method='post' action='<?=$this->url();?>'>
    <div class='col-md-12' style='margin-top:20px'></div>
    <div class='col-md-3'>
        Gebruikersnaam:    
    </div>
    <div class='col-md-9'>
        <input type='text' name='username' class='form-control' />
    </div><div class='col-md-12' style='margin-top:20px'></div>
    <div class='col-md-3'>
        Emailadres:    
    </div>
    <div class='col-md-9'>
        <input type='text' name='email' class='form-control'/>
    </div>
    <div class='col-md-12' style='margin-top:20px'></div>
    <div class='col-md-3'>
        Wachtwoord:
    </div>
    <div class='col-md-9'>
        <input type='password' name='password' class='form-control' placeholder='Wachtwoord'/><br/>
        <i>NB: AUB Leeg laten om automatisch te genereren.</i>
    </div>
    <div class='col-md-12' style='margin-top:20px'></div>
    <div class='col-md-3'>
        Bevoegdheid:    
    </div>
    <div class='col-md-9'>
        <select name='role' class='form-control'>
            <option value='super admin'>Super Admin</option>
            <option value='admin'>Admin</option>
            <option value='observer'>Gebruiker</option>
        </select>
    </div>
    <div class='col-md-12' style='margin-top:20px'></div>
    <div class='col-md-3'>
        Telefoonnummer:    
    </div>
    <div class='col-md-9'>
        <input type='text' name='number' class='form-control'/>
    </div>
    <div style='margin-top:20px;' class='col-md-12 text-center'>
        <input type='submit' class='btn btn-success' value='Opslaan'/>
    </div>
</form>