<div class='col-md-12'>
	<div class='col-md-9'>
		<h3>Recente users:</h3>
		<table class="table table-condensed table-hover">
		<tr class='active'>
			<th>Status</th>
			<th>Gebruikersnaam</th>
			<th>Email</th>
			<th>Telefoonnummer</th>
			<th>Rol</th>
			<th>Acties</th>
		</tr>
		<?php foreach($this->users as $user):?>
		<?php if($user->enabled==1): ?>
	    <tr>
		<?php else: ?>
		<tr class='danger'>
	    <?php endif; ?>
	        <td><?php if($user->enabled==1): ?>
			         Actief
			         <?php else: ?>
			         Non-actief
			         <?php endif; ?></td>
			<td><?=$user->username;?></td>
			<td><?=$user->email;?></td>
			<td><?=$user->telnr;?></td>
			<td><?=$user->role;?></td>
			<td>
			     <a href='<?=$this->baseUrl('admin/update-user/id/'.$user->user_id)?>'>Wijzigen</a> | 
			     <?php if($user->enabled==1): ?>
			         <a href='<?=$this->baseUrl('admin/toggle-user/id/'.$user->user_id)?>'>Deactiveer</a>
			         <?php else: ?>
			         <a href='<?=$this->baseUrl('admin/toggle-user/id/'.$user->user_id)?>'>Activeer</a>
			         <?php endif; ?>
			     <?php if($this->viewer->role=='super admin'):?>
			     | <a onclick="return confirm('Wilt u deze gebruiker verwijderen?');" href='<?=$this->baseUrl('admin/delete-user/id/'.$user->user_id)?>'>Verwijderen</a>
			     <?php endif; ?>
			          
			</td>
		</tr>
		<?php endforeach; ?>
	</table>
	<a href="<?= $this->baseUrl('admin/manage-users')?>" class='btn btn-primary' >Meer ></a>
	<h3>Laatste questionnaires:</h3>
		<table class="table table-condensed table-hover">
		<tr class='active'>
			<th>Vragenlijst</th>
			<th>Acties</th>
		</tr>
		<?php foreach($this->forms as $form):?>
		<?php if($form->started==1): ?>
		<tr class='success'>
		<?php else: ?>
	    <tr class='danger'>
	    <?php endif; ?>
			<td><?=$form->title;?></td>
			<td>
			     <a href='<?=$this->baseUrl('admin/view-questionnaire/id/'.$form->questionnaire_id)?>'>Bekijken</a> | 
			     <a href='<?=$this->baseUrl('admin/update-questionnaire/id/'.$form->questionnaire_id)?>'>Wijzigen</a> | 
			     <?php if($form->started==1): ?>
			         <a href='<?=$this->baseUrl('admin/toggle-questionnaire/id/'.$form->questionnaire_id)?>'>Stoppen</a>
			         <?php else: ?>
			         <a href='<?=$this->baseUrl('admin/toggle-questionnaire/id/'.$form->questionnaire_id)?>'>Starten</a>
			         <?php endif; ?>
			          | 
			     <a href='<?=$this->baseUrl('admin/results-questionnaire/id/'.$form->questionnaire_id)?>'>Statistieken bekijken</a>
			</td>
		</tr>
		<?php endforeach; ?>
	</table>
		<a href="<?= $this->baseUrl('admin/manage-questionnaires')?>" class='btn btn-primary' >Meer ></a>
	</div>
	<div class='col-md-3'>
	<h3>Huidige statistieken:</h3>
	<table  class="table table-condensed table-hover">
		<tr><td>Aantal users:</td><td><?= $this->userCount;?></td></tr>
		<tr><td>Aantal questionnaires:</td><td><?=$this->questionnaireCount?></td></tr>
		<tr><td>Aantal antwoorden:</td><td><?=$this->answerCount?></td></tr>
	</table>
	</div>
</div>