<form method="post" action="<?=$this->url()?>" role="form">
  <div class="form-group">
    <label for="username">Gebruikersnaam</label>
    <input name="username" type="text" class="form-control" style="border-radius:0px" id="username" placeholder="Gebruikersnaam">
  </div>
  <div class="form-group">
    <label for="password">Wachtwoord</label>
    <input name="password" type="password" class="form-control" style="border-radius:0px" id="password" placeholder="Wachtwoord">
  </div>
  <button type="submit" class="btn btn-sm btn-default">Inloggen</button>
</form>